#!/usr/bin/env python

import numpy
import matplotlib.pyplot as plot
import os

def make_image(x, y, name):
    plot.title('Cinema Database Example')
    plot.xlabel('Time')
    plot.ylabel('Amplitude = sin(x)')
    plot.grid(True, which='both')
    # plot.axhline(y=0)
    plot.ylim(top=1.1)
    plot.ylim(bottom=-1.1)
    plot.plot(x, y)
    plot.savefig(name)
    plot.clf()

outdir = "datasmall.cdb"
os.mkdir(outdir)

with open(os.path.join(outdir, "data.csv"), "w") as data:
    data.write("amplitude,FILE\n")
    xvals = numpy.arange(0, 10, 0.1)
    zvals = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9] 
 
    cur_image = 1
    for z in zvals: 
        yvals = numpy.sin(xvals)*z
        fname = "plot_{0:03d}.png".format(cur_image)
        make_image(xvals, yvals, os.path.join(outdir, fname ) )
        cur_image += 1
        data.write("{},{}\n".format(z,fname))

