#!/bin/bash

datadir="cinema_example_spreadsheet"

sizes=("big" "small")

for size in ${sizes[@]}; do
    source="data$size.cdb"
    destination="../$datadir/$size/experiment.cdb"

    echo "running $size dataset ..."
    echo "source:      $source"
    echo "destination: $destination"
    ./gen$size
    rm -rf $destination 
    mv $source $destination 
    echo
done
